"""remove the profile relationship foreignkey for test

Revision ID: 01036571a96e
Revises: 9ab32aeab1c5
Create Date: 2022-05-28 20:26:32.037185

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '01036571a96e'
down_revision = '9ab32aeab1c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_relationships_ibfk_2', 'user_relationships', type_='foreignkey')
    op.drop_constraint('user_relationships_ibfk_1', 'user_relationships', type_='foreignkey')
    op.drop_column('user_relationships', 'other_profile_id')
    op.drop_column('user_relationships', 'my_profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_relationships', sa.Column('my_profile_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('user_relationships', sa.Column('other_profile_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('user_relationships_ibfk_1', 'user_relationships', 'user_profiles', ['my_profile_id'], ['id'])
    op.create_foreign_key('user_relationships_ibfk_2', 'user_relationships', 'user_profiles', ['other_profile_id'], ['id'])
    # ### end Alembic commands ###
