"""add user's relationship

Revision ID: 04e3c4a2aaff
Revises: d615269dde6d
Create Date: 2022-05-08 18:39:58.172848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import server
from server.core.enums import RelationshipType

revision = '04e3c4a2aaff'
down_revision = 'd615269dde6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_relationships',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('my_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('other_profile_id', sa.BigInteger(), nullable=True),
    sa.Column('type', server.utils.IntTypeEnum(enum_class=RelationshipType), nullable=True),
    sa.Column('favorites', sa.Boolean(), nullable=True),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('is_forbidden', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['my_profile_id'], ['user_profiles.id'], ),
    sa.ForeignKeyConstraint(['other_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_relationships_id'), 'user_relationships', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_relationships_id'), table_name='user_relationships')
    op.drop_table('user_relationships')
    # ### end Alembic commands ###
