"""add redis_id for ChatHistory table.

Revision ID: 0da4687c0bad
Revises: d972c5300e38
Create Date: 2023-02-16 23:47:29.384286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0da4687c0bad'
down_revision = 'd972c5300e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('redis_id', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_chat_histories_redis_id'), 'chat_histories', ['redis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_redis_id'), table_name='chat_histories')
    op.drop_column('chat_histories', 'redis_id')
    # ### end Alembic commands ###
