"""apply timestampmixin to s3_media model

Revision ID: 17ea1dc47c30
Revises: 58ab47210e91
Create Date: 2022-05-22 21:02:09.418375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17ea1dc47c30'
down_revision = '58ab47210e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('s3_media', sa.Column('updated', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('s3_media', 'updated')
    op.drop_column('s3_media', 'created')
    # ### end Alembic commands ###
