"""add is_supseruser on User Table

Revision ID: 25297f334aac
Revises: 7aaecd558eee
Create Date: 2022-08-26 21:30:23.817718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25297f334aac'
down_revision = '7aaecd558eee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    # ### end Alembic commands ###
