"""fix timestamp mixin

Revision ID: 25f3d1d943f3
Revises: 406ff4dd2af4
Create Date: 2022-05-28 23:15:13.997019

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25f3d1d943f3'
down_revision = '406ff4dd2af4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_histories', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_histories', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('chat_room_user_mapping', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_room_user_mapping', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('chat_rooms', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_rooms', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('s3_media', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('s3_media', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profiles', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_profiles', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('s3_media', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('s3_media', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_rooms', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_rooms', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_room_user_mapping', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_room_user_mapping', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('chat_histories', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('chat_histories', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
