"""add is_active column to user_profile_image model

Revision ID: 2a77a1a72014
Revises: 472380e4064e
Create Date: 2022-05-22 21:15:42.926826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a77a1a72014'
down_revision = '472380e4064e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile_images', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profile_images', 'is_active')
    # ### end Alembic commands ###
