"""fix

Revision ID: 349801289749
Revises: fb7479baba5d
Create Date: 2022-11-27 16:18:20.187931

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '349801289749'
down_revision = 'fb7479baba5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('origin_uid', sa.String(length=32), nullable=True))
    op.create_foreign_key(None, 's3_media', 's3_media', ['origin_uid'], ['uid'])
    op.drop_column('s3_media', 'origin_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('origin_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 's3_media', type_='foreignkey')
    op.drop_column('s3_media', 'origin_uid')
    # ### end Alembic commands ###
