"""rollback is_active in UserProfile

Revision ID: 34f1817254f6
Revises: 9f8249a08c3e
Create Date: 2022-12-05 22:41:53.065209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f1817254f6'
down_revision = '9f8249a08c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'is_active')
    # ### end Alembic commands ###
