"""apply timestampmixin to all models

Revision ID: 472380e4064e
Revises: 17ea1dc47c30
Create Date: 2022-05-22 21:04:35.319068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '472380e4064e'
down_revision = '17ea1dc47c30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
