"""fix chathistory foreignkey

Revision ID: 58ab47210e91
Revises: 3a6b3d26efe8
Create Date: 2022-05-22 20:58:18.914247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58ab47210e91'
down_revision = '3a6b3d26efe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('room_id', sa.BigInteger(), nullable=False))
    op.drop_constraint('chat_histories_ibfk_1', 'chat_histories', type_='foreignkey')
    op.create_foreign_key(None, 'chat_histories', 'chat_rooms', ['room_id'], ['id'])
    op.drop_column('chat_histories', 'room_user_mapping_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('room_user_mapping_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.create_foreign_key('chat_histories_ibfk_1', 'chat_histories', 'chat_room_user_mapping', ['room_user_mapping_id'], ['id'])
    op.drop_column('chat_histories', 'room_id')
    # ### end Alembic commands ###
