"""add room type

Revision ID: 5994ccc6cdf2
Revises: c4a067c793b8
Create Date: 2022-12-11 17:19:14.219974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import server
from server.core.enums import ChatRoomType

revision = '5994ccc6cdf2'
down_revision = 'c4a067c793b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room_user_association', sa.Column('type', server.core.utils.IntTypeEnum(enum_class=ChatRoomType), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room_user_association', 'type')
    # ### end Alembic commands ###
