"""unique for user relationship

Revision ID: 5f5eef24524f
Revises: b1b59718e589
Create Date: 2022-12-27 23:25:21.358020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f5eef24524f'
down_revision = 'b1b59718e589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique relationship for both profile ids', 'user_relationships', ['my_profile_id', 'other_profile_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique relationship for both profile ids', 'user_relationships', type_='unique')
    # ### end Alembic commands ###
