"""fix user_profile_images model for inheriting

Revision ID: 71f8144b2697
Revises: 9d0804a804aa
Create Date: 2022-05-22 18:15:57.834208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from server.core import utils

# revision identifiers, used by Alembic.
from server.core.enums import ProfileImageType

revision = '71f8144b2697'
down_revision = '9d0804a804aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_images',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('type', utils.IntTypeEnum(enum_class=ProfileImageType), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['s3_media.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_images_id'), 'user_profile_images', ['id'], unique=False)
    op.drop_column('s3_media', 'user_profile_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('user_profile_id', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_profile_images_id'), table_name='user_profile_images')
    op.drop_table('user_profile_images')
    # ### end Alembic commands ###
