"""add  to ChatHistory

Revision ID: 758f74a0694c
Revises: 1cba91274e95
Create Date: 2022-11-07 23:21:37.103458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f74a0694c'
down_revision = '1cba91274e95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('user_profile_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'chat_histories', 'user_profiles', ['user_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_histories', type_='foreignkey')
    op.drop_column('chat_histories', 'user_profile_id')
    # ### end Alembic commands ###
