"""rollback

Revision ID: 78af8f3022b3
Revises: d92dacf3912c
Create Date: 2022-12-02 01:06:50.864895

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '78af8f3022b3'
down_revision = 'd92dacf3912c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history_files', 'chat_history_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.drop_constraint('chat_history_files_ibfk_3', 'chat_history_files', type_='foreignkey')
    op.create_foreign_key(None, 'chat_history_files', 'chat_histories', ['chat_history_id'], ['id'], ondelete='CASCADE')
    op.alter_column('s3_media', 'filepath',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.drop_constraint('s3_media_ibfk_2', 's3_media', type_='foreignkey')
    op.create_foreign_key(None, 's3_media', 'user_profiles', ['uploaded_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 's3_media', type_='foreignkey')
    op.create_foreign_key('s3_media_ibfk_2', 's3_media', 'users', ['uploaded_by_id'], ['id'])
    op.alter_column('s3_media', 'filepath',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.drop_constraint(None, 'chat_history_files', type_='foreignkey')
    op.create_foreign_key('chat_history_files_ibfk_3', 'chat_history_files', 'chat_histories', ['chat_history_id'], ['id'])
    op.alter_column('chat_history_files', 'chat_history_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
