"""add nickname, room name for association relationship

Revision ID: 820fc8988bfc
Revises: 34f1817254f6
Create Date: 2022-12-06 23:03:26.644148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820fc8988bfc'
down_revision = '34f1817254f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room_user_association', sa.Column('room_name', sa.String(length=30), nullable=False))
    op.add_column('user_relationships', sa.Column('other_profile_nickname', sa.String(length=30), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_relationships', 'other_profile_nickname')
    op.drop_column('chat_room_user_association', 'room_name')
    # ### end Alembic commands ###
