"""add 

Revision ID: 837526499d88
Revises: c14a4d000e96
Create Date: 2022-11-15 23:08:19.279278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837526499d88'
down_revision = 'c14a4d000e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_user_association',
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['chat_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', 'user_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history_user_association')
    # ### end Alembic commands ###
