"""add relationships for user profile with foreign key

Revision ID: 875da1dda0ba
Revises: 01036571a96e
Create Date: 2022-05-28 20:27:50.596889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '875da1dda0ba'
down_revision = '01036571a96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_relationships', sa.Column('my_profile_id', sa.BigInteger(), nullable=False))
    op.add_column('user_relationships', sa.Column('other_profile_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'user_relationships', 'user_profiles', ['my_profile_id'], ['id'])
    op.create_foreign_key(None, 'user_relationships', 'user_profiles', ['other_profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_relationships', type_='foreignkey')
    op.drop_constraint(None, 'user_relationships', type_='foreignkey')
    op.drop_column('user_relationships', 'other_profile_id')
    op.drop_column('user_relationships', 'my_profile_id')
    # ### end Alembic commands ###
