"""add 

Revision ID: 8815419b9795
Revises: 758f74a0694c
Create Date: 2022-11-08 17:30:56.177161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8815419b9795'
down_revision = '758f74a0694c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_user_association',
    sa.Column('history_id', sa.BigInteger(), nullable=False),
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['chat_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', 'user_profile_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history_user_association')
    # ### end Alembic commands ###
