"""add index for room_id on ChatHistory

Revision ID: 8c50e48e88fb
Revises: 0da4687c0bad
Create Date: 2023-03-14 00:05:31.801714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c50e48e88fb'
down_revision = '0da4687c0bad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_histories_room_id'), 'chat_histories', ['room_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_room_id'), table_name='chat_histories')
    # ### end Alembic commands ###
