"""add origin column for S3Media

Revision ID: 9975809e8776
Revises: 494ba59742ef
Create Date: 2022-11-27 16:00:49.991353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9975809e8776'
down_revision = '494ba59742ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('origin_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 's3_media', 's3_media', ['origin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 's3_media', type_='foreignkey')
    op.drop_column('s3_media', 'origin_id')
    # ### end Alembic commands ###
