"""fix model

Revision ID: 9ab32aeab1c5
Revises: 2a77a1a72014
Create Date: 2022-05-28 19:37:56.190682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ab32aeab1c5'
down_revision = '2a77a1a72014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('use_type', sa.String(length=50), nullable=True))
    op.drop_column('s3_media', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('type', mysql.VARCHAR(length=50), nullable=True))
    op.drop_column('s3_media', 'use_type')
    # ### end Alembic commands ###
