"""fix ondelete

Revision ID: 9bd0ecff721f
Revises: 361aca0d0626
Create Date: 2022-08-31 16:42:52.655340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bd0ecff721f'
down_revision = '361aca0d0626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_room_user_association_ibfk_1', 'chat_room_user_association', type_='foreignkey')
    op.drop_constraint('chat_room_user_association_ibfk_2', 'chat_room_user_association', type_='foreignkey')
    op.create_foreign_key(None, 'chat_room_user_association', 'user_profiles', ['user_profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chat_room_user_association', 'chat_rooms', ['room_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_profile_images_ibfk_2', 'user_profile_images', type_='foreignkey')
    op.create_foreign_key(None, 'user_profile_images', 'user_profiles', ['user_profile_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile_images', type_='foreignkey')
    op.create_foreign_key('user_profile_images_ibfk_2', 'user_profile_images', 'user_profiles', ['user_profile_id'], ['id'])
    op.drop_constraint(None, 'chat_room_user_association', type_='foreignkey')
    op.drop_constraint(None, 'chat_room_user_association', type_='foreignkey')
    op.create_foreign_key('chat_room_user_association_ibfk_2', 'chat_room_user_association', 'user_profiles', ['user_profile_id'], ['id'])
    op.create_foreign_key('chat_room_user_association_ibfk_1', 'chat_room_user_association', 'chat_rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
