"""add service model

Revision ID: 9d0804a804aa
Revises: 1b09278a4268
Create Date: 2022-05-22 16:28:46.657928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d0804a804aa'
down_revision = '1b09278a4268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_rooms_id'), 'chat_rooms', ['id'], unique=False)
    op.create_table('s3_media',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('bucket_name', sa.String(length=50), nullable=False),
    sa.Column('file_key', sa.String(length=45), nullable=False),
    sa.Column('file_path', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_s3_media_id'), 's3_media', ['id'], unique=False)
    op.create_table('chat_room_user_mapping',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('user_profile_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_room_user_mapping_id'), 'chat_room_user_mapping', ['id'], unique=False)
    op.create_table('chat_histories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('room_user_mapping_id', sa.BigInteger(), nullable=False),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('s3_media_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['room_user_mapping_id'], ['chat_room_user_mapping.id'], ),
    sa.ForeignKeyConstraint(['s3_media_id'], ['s3_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_histories_id'), 'chat_histories', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_histories_id'), table_name='chat_histories')
    op.drop_table('chat_histories')
    op.drop_index(op.f('ix_chat_room_user_mapping_id'), table_name='chat_room_user_mapping')
    op.drop_table('chat_room_user_mapping')
    op.drop_index(op.f('ix_s3_media_id'), table_name='s3_media')
    op.drop_table('s3_media')
    op.drop_index(op.f('ix_chat_rooms_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
