"""add chat room

Revision ID: 9eaec211dc4d
Revises: 1b09278a4268
Create Date: 2022-05-08 19:12:44.315886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eaec211dc4d'
down_revision = '1b09278a4268'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
