"""add index=True to created column

Revision ID: 9f8249a08c3e
Revises: d90cb0e00de4
Create Date: 2022-12-05 21:51:53.657685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8249a08c3e'
down_revision = 'd90cb0e00de4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chat_histories_created'), 'chat_histories', ['created'], unique=False)
    op.create_index(op.f('ix_chat_room_user_association_created'), 'chat_room_user_association', ['created'], unique=False)
    op.create_index(op.f('ix_chat_rooms_created'), 'chat_rooms', ['created'], unique=False)
    op.create_index(op.f('ix_s3_media_created'), 's3_media', ['created'], unique=False)
    op.create_index(op.f('ix_user_profiles_created'), 'user_profiles', ['created'], unique=False)
    op.create_index(op.f('ix_user_sessions_created'), 'user_sessions', ['created'], unique=False)
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.drop_index(op.f('ix_user_sessions_created'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_profiles_created'), table_name='user_profiles')
    op.drop_index(op.f('ix_s3_media_created'), table_name='s3_media')
    op.drop_index(op.f('ix_chat_rooms_created'), table_name='chat_rooms')
    op.drop_index(op.f('ix_chat_room_user_association_created'), table_name='chat_room_user_association')
    op.drop_index(op.f('ix_chat_histories_created'), table_name='chat_histories')
    # ### end Alembic commands ###
