"""add unique for identity_id

Revision ID: b1b59718e589
Revises: efdc755addf3
Create Date: 2022-12-27 22:11:15.109851

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1b59718e589'
down_revision = 'efdc755addf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'identity_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.create_unique_constraint(None, 'user_profiles', ['identity_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='unique')
    op.alter_column('user_profiles', 'identity_id',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###
