"""add cascade option

Revision ID: b1babd717753
Revises: 7cefcb50533a
Create Date: 2022-06-01 13:17:08.645786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1babd717753'
down_revision = '7cefcb50533a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
