"""add `ChatHistoryFile`

Revision ID: c14a4d000e96
Revises: fc7b0c152897
Create Date: 2022-11-12 12:38:06.629626

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c14a4d000e96'
down_revision = 'fc7b0c152897'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('chat_history_id', sa.BigInteger(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_history_id'], ['chat_histories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['s3_media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order')
    )
    op.drop_constraint('chat_histories_ibfk_2', 'chat_histories', type_='foreignkey')
    op.drop_column('chat_histories', 's3_media_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('s3_media_id', mysql.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('chat_histories_ibfk_2', 'chat_histories', 's3_media', ['s3_media_id'], ['id'])
    op.drop_table('chat_history_files')
    # ### end Alembic commands ###
