"""set nullable to nickname and room name for association relation.

Revision ID: c4a067c793b8
Revises: 820fc8988bfc
Create Date: 2022-12-07 01:40:15.348915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4a067c793b8'
down_revision = '820fc8988bfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_room_user_association', 'room_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_relationships', 'other_profile_nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_relationships', 'other_profile_nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('chat_room_user_association', 'room_name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    # ### end Alembic commands ###
