"""set unique for chat_history_id and order in ChatHistoryFile

Revision ID: d3ba8587e1fd
Revises: 01286c04009e
Create Date: 2022-12-04 19:39:25.558884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3ba8587e1fd'
down_revision = '01286c04009e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('order', table_name='chat_history_files')
    op.create_unique_constraint('unique order for chat_history_id', 'chat_history_files', ['chat_history_id', 'order'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique order for chat_history_id', 'chat_history_files', type_='unique')
    op.create_index('order', 'chat_history_files', ['order'], unique=False)
    # ### end Alembic commands ###
