"""add user_id for user_profiles

Revision ID: d615269dde6d
Revises: 95ba96b5a59f
Create Date: 2022-05-08 14:47:12.741884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd615269dde6d'
down_revision = '95ba96b5a59f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('user_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.drop_column('user_profiles', 'user_id')
    # ### end Alembic commands ###
