"""add `is_read` column to ChatHistoryUserAssociation

Revision ID: d79ff50606ce
Revises: 837526499d88
Create Date: 2022-11-15 23:36:57.052399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79ff50606ce'
down_revision = '837526499d88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history_user_association', sa.Column('is_read', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history_user_association', 'is_read')
    # ### end Alembic commands ###
