"""add is_active to ChatHistory

Revision ID: d90cb0e00de4
Revises: 6595a4f71b35
Create Date: 2022-12-05 12:11:59.497292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd90cb0e00de4'
down_revision = '6595a4f71b35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('chat_history_files', 'is_active')
    op.drop_column('user_profile_images', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile_images', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('chat_history_files', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('chat_histories', 'is_active')
    # ### end Alembic commands ###
