"""set unique for ChatRoomUserAssociation

Revision ID: d972c5300e38
Revises: e5e1d067f3c8
Create Date: 2023-02-11 15:14:48.908313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd972c5300e38'
down_revision = 'e5e1d067f3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique association for both room_id and user_profile_id.', 'chat_room_user_association', ['room_id', 'user_profile_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique association for both room_id and user_profile_id.', 'chat_room_user_association', type_='unique')
    # ### end Alembic commands ###
