"""add  to ChatRoom

Revision ID: db38e0bcf7ae
Revises: de7833ef746f
Create Date: 2022-11-05 01:12:30.518836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db38e0bcf7ae'
down_revision = 'de7833ef746f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_rooms', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_rooms', 'is_active')
    # ### end Alembic commands ###
