"""add type for chat history

Revision ID: e5e1d067f3c8
Revises: 670b2b5f985a
Create Date: 2023-01-18 23:33:00.422551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
import server
from server.core.enums import ChatHistoryType

revision = 'e5e1d067f3c8'
down_revision = '670b2b5f985a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_histories', sa.Column('type', server.core.utils.IntTypeEnum(enum_class=ChatHistoryType), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_histories', 'type')
    # ### end Alembic commands ###
