"""add identity_id for UserProfile

Revision ID: efdc755addf3
Revises: e68bbe70d208
Create Date: 2022-12-27 21:51:56.629508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efdc755addf3'
down_revision = 'e68bbe70d208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('identity_id', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'identity_id')
    # ### end Alembic commands ###
