"""fix not nullable fields

Revision ID: f89ad05e8d41
Revises: 04e3c4a2aaff
Create Date: 2022-05-08 18:46:59.254511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f89ad05e8d41'
down_revision = '04e3c4a2aaff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('user_profiles', 'nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('user_profiles', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_profiles', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_profiles', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('user_relationships', 'my_profile_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('user_relationships', 'other_profile_id',
               existing_type=mysql.BIGINT(),
               nullable=False)
    op.alter_column('user_relationships', 'type',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('user_relationships', 'favorites',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_relationships', 'is_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_relationships', 'is_forbidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('user_relationships', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'uid',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=30),
               nullable=False)
    op.alter_column('users', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'is_staff',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'mobile',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('users', 'uid',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_relationships', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_relationships', 'is_forbidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_relationships', 'is_hidden',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_relationships', 'favorites',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_relationships', 'type',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('user_relationships', 'other_profile_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('user_relationships', 'my_profile_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    op.alter_column('user_profiles', 'updated',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('user_profiles', 'created',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('user_profiles', 'is_active',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_profiles', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('user_profiles', 'nickname',
               existing_type=mysql.VARCHAR(length=30),
               nullable=True)
    op.alter_column('user_profiles', 'user_id',
               existing_type=mysql.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
