"""add uid column for S3Media

Revision ID: fb7479baba5d
Revises: 9975809e8776
Create Date: 2022-11-27 16:08:27.403363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7479baba5d'
down_revision = '9975809e8776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_media', sa.Column('uid', sa.String(length=32), nullable=False))
    op.create_unique_constraint(None, 's3_media', ['uid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 's3_media', type_='unique')
    op.drop_column('s3_media', 'uid')
    # ### end Alembic commands ###
