"""remove ChatHistoryUserAssociation table

Revision ID: fc7b0c152897
Revises: 8815419b9795
Create Date: 2022-11-11 19:16:06.205459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc7b0c152897'
down_revision = '8815419b9795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_history_user_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history_user_association',
    sa.Column('history_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('user_profile_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['history_id'], ['chat_histories.id'], name='chat_history_user_association_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_profile_id'], ['user_profiles.id'], name='chat_history_user_association_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('history_id', 'user_profile_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
